Building DAG of jobs...
Using shell: /bin/bash
Provided cores: 1
Rules claiming more threads will be scaled down.
Job counts:
	count	jobs
	1	all
	1	pdftext
	1	tsaBE
	1	tsaZH
	4

[Sat Oct 13 17:21:49 2018]
rule tsaZH:
    input: output/data_ZH.csv, input/TSA_ZH.py
    output: output/finaldata_ZH.csv, output/ZH/plot/figACF_WN.pdf, output/ZH/plot/figACF.pdf, output/ZH/plot/figError.pdf, output/ZH/plot/figModel.pdf, output/ZH/plot/figOrig.pdf, output/ZH/plot/figPACF_WN.pdf, output/ZH/plot/figPACF.pdf, output/ZH/plot/figSeason.pdf, output/ZH/plot/figTrend.pdf, output/ZH/table/aicc_df.tex, output/ZH/table/error_table.tex, output/ZH/table/trend_table.tex, output/ZH/table/vectorcorr_df.tex
    jobid: 1

[Sat Oct 13 17:23:07 2018]
Finished job 1.
1 of 4 steps (25%) done

[Sat Oct 13 17:23:07 2018]
rule tsaBE:
    input: output/data_BE.csv, input/TSA_BE.py
    output: output/finaldata_BE.csv, output/BE/plot/figACF_WN.pdf, output/BE/plot/figACF.pdf, output/BE/plot/figError.pdf, output/BE/plot/figModel.pdf, output/BE/plot/figOrig.pdf, output/BE/plot/figPACF_WN.pdf, output/BE/plot/figPACF.pdf, output/BE/plot/figSeason.pdf, output/BE/plot/figTrend.pdf, output/BE/table/aicc_df.tex, output/BE/table/error_table.tex, output/BE/table/trend_table.tex, output/BE/table/vectorcorr_df.tex
    jobid: 4

    [Sat Oct 13 17:24:32 2018]
    Error in rule tsaBE:
        jobid: 4
        output: output/finaldata_BE.csv, output/BE/plot/figACF_WN.pdf, output/BE/plot/figACF.pdf, output/BE/plot/figError.pdf, output/BE/plot/figModel.pdf, output/BE/plot/figOrig.pdf, output/BE/plot/figPACF_WN.pdf, output/BE/plot/figPACF.pdf, output/BE/plot/figSeason.pdf, output/BE/plot/figTrend.pdf, output/BE/table/aicc_df.tex, output/BE/table/error_table.tex, output/BE/table/trend_table.tex, output/BE/table/vectorcorr_df.tex

RuleException:
CalledProcessError in line 83 of /Users/jasminmaag/pp4rs/playground/Final_Project/Snakefile:
Command ' set -euo pipefail;  /anaconda3/bin/python /Users/jasminmaag/pp4rs/playground/Final_Project/input/.snakemake.ue1yhsf_.TSA_BE.py ' returned non-zero exit status 1.
  File "/Users/jasminmaag/pp4rs/playground/Final_Project/Snakefile", line 83, in __rule_tsaBE
  File "/anaconda3/lib/python3.6/concurrent/futures/thread.py", line 56, in run
Removing output files of failed job tsaBE since they might be corrupted:
output/BE/plot/figACF.pdf, output/BE/plot/figError.pdf, output/BE/plot/figOrig.pdf, output/BE/plot/figPACF.pdf, output/BE/plot/figSeason.pdf, output/BE/plot/figTrend.pdf, output/BE/table/trend_table.tex, output/BE/table/vectorcorr_df.tex
Shutting down, this might take some time.
Exiting because a job execution failed. Look above for error message
Complete log: /Users/jasminmaag/pp4rs/playground/Final_Project/.snakemake/log/2018-10-13T172149.394843.snakemake.log
